object Versions {
    const val coroutinesVersion = "1.3.9"
    const val androidxCore = "1.7.0"
    const val androidxAppcompat = "1.5.1"
    const val androidxConstraintLayout = "2.1.4"
    const val androidxNavigation = "2.5.2"
    const val jUnit = "4.13.2"
    const val androidxJUnit = "1.1.3"
    const val androidxEspresso = "3.4.0"
    const val materialDesign = "1.5.0-alpha04"
    const val pluginKotlin = "1.7.20"
    const val pluginAndroid = "7.2.1"
    const val retrofit = "2.9.0"
    const val timber = "4.7.1"
    const val koin = "3.1.4"
    const val coroutines = "1.3.9"
    const val lifecycle = "2.5.1"
    const val arrow = "1.1.2"
    const val jackson = "2.9.0"
    const val jacksonKotlin = "2.13.4"
    const val webkit = "1.5.0"
    const val viewpager2 = "1.1.0-beta01"
    const val glide = "4.12.0"
    const val shimmer = "0.5.0"
    const val prettyTime = "5.0.4.Final"
    const val swipeRefreshLayout = "1.1.0"
}